### PR TITLE
Kotlin Support

### PR DESCRIPTION
**Pull request by kevcodez**

### CODE REVIEW

**Comment by kevcodez** [comment]
If there is anything to add, please let me know ;)

Kotlin Grammar https://kotlinlang.org/docs/reference/grammar.html

**Comment by kevcodez** [comment]
@AndiDittrich would love to see a new plugin release for wordpress, if possible :)

**Comment by AndiDittrich** [comment]
Do you have any kotlin example code owned by yours ? the example codes license is not compatible

**Comment by kevcodez** [comment]
What about this one https://try.kotlinlang.org/#/Examples/Longer%20examples/HTML%20Builder/HTML%20Builder.kt ? From the official Kotlin page

**Comment by AndiDittrich** [comment]
need something with MIT license or similar .. a small testcase will be sufficient.

**Comment by kevcodez** [comment]
Just wrote some sample code, free to use.

```
package com.example

import java.time.LocalDate

data class Person(var firstName: String, var lastName: String, var birthdate: LocalDate) {

    fun getAge(): Int {
        return LocalDate.now().year - birthdate.year;
    }

}

fun main(args: Array<String>) {
    val person1 = Person("Samuel", "Jackson", LocalDate.of(1948, 12, 21));
    val person2 = Person("Quentin", "Tarantino", LocalDate.of(1963, 3, 27))

    val persons = listOf<Person>(person1, person2)

    val personsAbove50 = persons.filter { it.getAge() > 50 }

    println(personsAbove50)

    println("First Name: ${person1.firstName}")

    val jsonString = """[
      {"firstName":"Samuel", "lastName": "Jackson"},
      {"firstName":"Quentin", "lastName": "Tarantino"}
    ]"""

    println(jsonString)
}

```

**Comment by AndiDittrich** [comment]
Dear kevcodez,

i've just release EnlighterJS **v2.11.0** including your Kotlin language support. https://enlighterjs.org/Language.Kotlin.html

it will be added to the next Enlighter WordPress Release

br, Andi

**Comment by AndiDittrich** [comment]
https://github.com/AndiDittrich/WordPress.Enlighter

Added to v3.5-BETA1

**Pull request merged**
