### PR TITLE
Create cython.html

### PR DESCRIPTION
**Pull request by DevynCJohnson**
I provided a variety of sample Cython code to demonstrate preprocessor statements, C-datatypes, general/basic syntax, etc.

Feel free to request modifications, additional code, etc.

### CODE REVIEW

**Comment by AndiDittrich** [comment]
Thank you!

**Comment by DevynCJohnson** [comment]
No problem. (^u^)

**Comment by DevynCJohnson** [comment]
When I add the demo code as HTML files, do you want me to commit the code using the "ci skip" flag?

**Comment by AndiDittrich** [comment]
No, it's not required. currently there is no CI service running

**Pull request merged**
