### PR TITLE
Create Cython.js

### PR DESCRIPTION
**Pull request by DevynCJohnson**
Cython is a superset of Python with additional features/abilities for C/C++ programming ( http://cython.org/ ).
I would like to contribute to more "language" files in EnlighterJS. Please feel free to provide feedback so that I can continue to help you (and comply with your coding-standards) with your project.
This "Cython.js" file is a derivative of your "Python.js" file.

### CODE REVIEW

**Comment by AndiDittrich** [comment]
Dear DevynCJohnson,

thanks for your contribution. do you have any language testcases which can be used as demo and for verification (.e.g somethink like http://enlighterjs.andidittrich.de/Language.Python.html) ? 

best regards, Andi

**Comment by DevynCJohnson** [comment]
Yes, I have Cython code that can be used as a small demo. How would you like me to submit the demo code? What format would you like (i.e. Cython code as plain-text, HTML page with code in pre tags, etc.)?

Would it be okay with you if I contribute additional programming languages in the future? Do you have standards/rules as to what languages are acceptable for being supported by EnlighterJS?

**Comment by AndiDittrich** [comment]
All language testcases/examples are located in `Resources/TestcaseData/<lang>.html` as html snippet (like https://github.com/AndiDittrich/EnlighterJS/blob/master/Resources/TestcaseData/python.html).
They have to contain a simple inline example as well as a complex language testcase including as much as practicable language elements. Please add it as pull request.
Especially basic language elements are important to test the rules and the tokenizer. For example

**PHP**
```php
/** String's */
echo 'this is a simple string';

echo 'You can also have embedded newlines in 
strings this way as it is \'
okay to do'; // Don't you agree

// Outputs: Arnold once said: "I'll be back"
echo 'Arnold once said: "I\'ll be back"';

/** Numbers */

$a = 1234; // decimal number
$a = -123; // a negative number
$a = 0123; // octal number (equivalent to 83 decimal)
$a = 0x1A; // hexadecimal number (equivalent to 26 decimal)
$a = 1.234; 
$b = 1.2e3; 
$c = 7E-10;

```

I will add a detailed description/list to the [Contribution Guidelines](https://github.com/AndiDittrich/EnlighterJS/blob/master/CONTRIBUTE.md) later as well as some standards/rules.

I'm looking forward for any language contribution. Generally language files should be as small as possible (e.g. use regex instead of keywords).
What languages do you plan to contribute ? Maybe i should create a wiki page for organization pupose ?

**Comment by DevynCJohnson** [comment]
Okay, I created the demo Cython code. I am more than happy to make any modifications to the demo as you wish.

If it is okay with you, I would like to add
* Squirrel
* XNA
* Basic/Gambas/Visual-Basic
* and more

I use EnlighterJS on my website (DCJTech.info), which is a website about computers and programming. Obviously, I see a need for additional language support since I have articles discussing a variety of languages.

I enjoy programming and I love to help with programming projects. Please feel free to tell me if I ever do something wrong in your project. I will not be offended. I want to help while complying with your coding standards and program structure. Feel free to communicate with me using my personal email address (DevynCJohnson@Gmail.com), if that would be more convenient for you.

**Comment by AndiDittrich** [comment]
Sounds great!

I've optimized your cython code: https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Language/Cython.js

you've only added additional keywords, right ?

**Comment by DevynCJohnson** [comment]
Yes, I only added additional keywords. Cython is a subset of Python with additional C-like features.

**Pull request merged**
